/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowRouteImport } from './routes/workflow'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DiagnosisRouteImport } from './routes/diagnosis'
import { Route as AnatomyRouteImport } from './routes/anatomy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkflowSummaryRouteImport } from './routes/workflow.summary'
import { Route as ToolsRubberDamRouteImport } from './routes/tools.rubber-dam'
import { Route as ToolsIrrigationRouteImport } from './routes/tools.irrigation'
import { Route as ToolsFileCalculatorRouteImport } from './routes/tools.file-calculator'

const WorkflowRoute = WorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosisRoute = DiagnosisRouteImport.update({
  id: '/diagnosis',
  path: '/diagnosis',
  getParentRoute: () => rootRouteImport,
} as any)
const AnatomyRoute = AnatomyRouteImport.update({
  id: '/anatomy',
  path: '/anatomy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowSummaryRoute = WorkflowSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => WorkflowRoute,
} as any)
const ToolsRubberDamRoute = ToolsRubberDamRouteImport.update({
  id: '/rubber-dam',
  path: '/rubber-dam',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsIrrigationRoute = ToolsIrrigationRouteImport.update({
  id: '/irrigation',
  path: '/irrigation',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsFileCalculatorRoute = ToolsFileCalculatorRouteImport.update({
  id: '/file-calculator',
  path: '/file-calculator',
  getParentRoute: () => ToolsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anatomy': typeof AnatomyRoute
  '/diagnosis': typeof DiagnosisRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/tools': typeof ToolsRouteWithChildren
  '/workflow': typeof WorkflowRouteWithChildren
  '/tools/file-calculator': typeof ToolsFileCalculatorRoute
  '/tools/irrigation': typeof ToolsIrrigationRoute
  '/tools/rubber-dam': typeof ToolsRubberDamRoute
  '/workflow/summary': typeof WorkflowSummaryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anatomy': typeof AnatomyRoute
  '/diagnosis': typeof DiagnosisRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/tools': typeof ToolsRouteWithChildren
  '/workflow': typeof WorkflowRouteWithChildren
  '/tools/file-calculator': typeof ToolsFileCalculatorRoute
  '/tools/irrigation': typeof ToolsIrrigationRoute
  '/tools/rubber-dam': typeof ToolsRubberDamRoute
  '/workflow/summary': typeof WorkflowSummaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anatomy': typeof AnatomyRoute
  '/diagnosis': typeof DiagnosisRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/tools': typeof ToolsRouteWithChildren
  '/workflow': typeof WorkflowRouteWithChildren
  '/tools/file-calculator': typeof ToolsFileCalculatorRoute
  '/tools/irrigation': typeof ToolsIrrigationRoute
  '/tools/rubber-dam': typeof ToolsRubberDamRoute
  '/workflow/summary': typeof WorkflowSummaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anatomy'
    | '/diagnosis'
    | '/login'
    | '/profile'
    | '/signup'
    | '/tools'
    | '/workflow'
    | '/tools/file-calculator'
    | '/tools/irrigation'
    | '/tools/rubber-dam'
    | '/workflow/summary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anatomy'
    | '/diagnosis'
    | '/login'
    | '/profile'
    | '/signup'
    | '/tools'
    | '/workflow'
    | '/tools/file-calculator'
    | '/tools/irrigation'
    | '/tools/rubber-dam'
    | '/workflow/summary'
  id:
    | '__root__'
    | '/'
    | '/anatomy'
    | '/diagnosis'
    | '/login'
    | '/profile'
    | '/signup'
    | '/tools'
    | '/workflow'
    | '/tools/file-calculator'
    | '/tools/irrigation'
    | '/tools/rubber-dam'
    | '/workflow/summary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnatomyRoute: typeof AnatomyRoute
  DiagnosisRoute: typeof DiagnosisRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  ToolsRoute: typeof ToolsRouteWithChildren
  WorkflowRoute: typeof WorkflowRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflow': {
      id: '/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof WorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnosis': {
      id: '/diagnosis'
      path: '/diagnosis'
      fullPath: '/diagnosis'
      preLoaderRoute: typeof DiagnosisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anatomy': {
      id: '/anatomy'
      path: '/anatomy'
      fullPath: '/anatomy'
      preLoaderRoute: typeof AnatomyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow/summary': {
      id: '/workflow/summary'
      path: '/summary'
      fullPath: '/workflow/summary'
      preLoaderRoute: typeof WorkflowSummaryRouteImport
      parentRoute: typeof WorkflowRoute
    }
    '/tools/rubber-dam': {
      id: '/tools/rubber-dam'
      path: '/rubber-dam'
      fullPath: '/tools/rubber-dam'
      preLoaderRoute: typeof ToolsRubberDamRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/irrigation': {
      id: '/tools/irrigation'
      path: '/irrigation'
      fullPath: '/tools/irrigation'
      preLoaderRoute: typeof ToolsIrrigationRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/file-calculator': {
      id: '/tools/file-calculator'
      path: '/file-calculator'
      fullPath: '/tools/file-calculator'
      preLoaderRoute: typeof ToolsFileCalculatorRouteImport
      parentRoute: typeof ToolsRoute
    }
  }
}

interface ToolsRouteChildren {
  ToolsFileCalculatorRoute: typeof ToolsFileCalculatorRoute
  ToolsIrrigationRoute: typeof ToolsIrrigationRoute
  ToolsRubberDamRoute: typeof ToolsRubberDamRoute
}

const ToolsRouteChildren: ToolsRouteChildren = {
  ToolsFileCalculatorRoute: ToolsFileCalculatorRoute,
  ToolsIrrigationRoute: ToolsIrrigationRoute,
  ToolsRubberDamRoute: ToolsRubberDamRoute,
}

const ToolsRouteWithChildren = ToolsRoute._addFileChildren(ToolsRouteChildren)

interface WorkflowRouteChildren {
  WorkflowSummaryRoute: typeof WorkflowSummaryRoute
}

const WorkflowRouteChildren: WorkflowRouteChildren = {
  WorkflowSummaryRoute: WorkflowSummaryRoute,
}

const WorkflowRouteWithChildren = WorkflowRoute._addFileChildren(
  WorkflowRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnatomyRoute: AnatomyRoute,
  DiagnosisRoute: DiagnosisRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  ToolsRoute: ToolsRouteWithChildren,
  WorkflowRoute: WorkflowRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
