/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowRouteImport } from './routes/workflow'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DiagnosisRouteImport } from './routes/diagnosis'
import { Route as AnatomyRouteImport } from './routes/anatomy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as WorkflowSummaryRouteImport } from './routes/workflow_.summary'
import { Route as ToolsRubberDamRouteImport } from './routes/tools.rubber-dam'
import { Route as ToolsIrrigationRouteImport } from './routes/tools.irrigation'
import { Route as ToolsFileCalculatorRouteImport } from './routes/tools.file-calculator'
import { Route as CasesCaseIdRouteImport } from './routes/cases.$caseId'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'

const WorkflowRoute = WorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosisRoute = DiagnosisRouteImport.update({
  id: '/diagnosis',
  path: '/diagnosis',
  getParentRoute: () => rootRouteImport,
} as any)
const AnatomyRoute = AnatomyRouteImport.update({
  id: '/anatomy',
  path: '/anatomy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowSummaryRoute = WorkflowSummaryRouteImport.update({
  id: '/workflow_/summary',
  path: '/workflow/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRubberDamRoute = ToolsRubberDamRouteImport.update({
  id: '/tools/rubber-dam',
  path: '/tools/rubber-dam',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIrrigationRoute = ToolsIrrigationRouteImport.update({
  id: '/tools/irrigation',
  path: '/tools/irrigation',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsFileCalculatorRoute = ToolsFileCalculatorRouteImport.update({
  id: '/tools/file-calculator',
  path: '/tools/file-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesCaseIdRoute = CasesCaseIdRouteImport.update({
  id: '/cases/$caseId',
  path: '/cases/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anatomy': typeof AnatomyRoute
  '/diagnosis': typeof DiagnosisRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/workflow': typeof WorkflowRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/tools/file-calculator': typeof ToolsFileCalculatorRoute
  '/tools/irrigation': typeof ToolsIrrigationRoute
  '/tools/rubber-dam': typeof ToolsRubberDamRoute
  '/workflow/summary': typeof WorkflowSummaryRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anatomy': typeof AnatomyRoute
  '/diagnosis': typeof DiagnosisRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/workflow': typeof WorkflowRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/tools/file-calculator': typeof ToolsFileCalculatorRoute
  '/tools/irrigation': typeof ToolsIrrigationRoute
  '/tools/rubber-dam': typeof ToolsRubberDamRoute
  '/workflow/summary': typeof WorkflowSummaryRoute
  '/tools': typeof ToolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anatomy': typeof AnatomyRoute
  '/diagnosis': typeof DiagnosisRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/workflow': typeof WorkflowRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/tools/file-calculator': typeof ToolsFileCalculatorRoute
  '/tools/irrigation': typeof ToolsIrrigationRoute
  '/tools/rubber-dam': typeof ToolsRubberDamRoute
  '/workflow_/summary': typeof WorkflowSummaryRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anatomy'
    | '/diagnosis'
    | '/login'
    | '/profile'
    | '/signup'
    | '/verify-email'
    | '/workflow'
    | '/auth/callback'
    | '/cases/$caseId'
    | '/tools/file-calculator'
    | '/tools/irrigation'
    | '/tools/rubber-dam'
    | '/workflow/summary'
    | '/tools/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anatomy'
    | '/diagnosis'
    | '/login'
    | '/profile'
    | '/signup'
    | '/verify-email'
    | '/workflow'
    | '/auth/callback'
    | '/cases/$caseId'
    | '/tools/file-calculator'
    | '/tools/irrigation'
    | '/tools/rubber-dam'
    | '/workflow/summary'
    | '/tools'
  id:
    | '__root__'
    | '/'
    | '/anatomy'
    | '/diagnosis'
    | '/login'
    | '/profile'
    | '/signup'
    | '/verify-email'
    | '/workflow'
    | '/auth/callback'
    | '/cases/$caseId'
    | '/tools/file-calculator'
    | '/tools/irrigation'
    | '/tools/rubber-dam'
    | '/workflow_/summary'
    | '/tools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnatomyRoute: typeof AnatomyRoute
  DiagnosisRoute: typeof DiagnosisRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  WorkflowRoute: typeof WorkflowRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CasesCaseIdRoute: typeof CasesCaseIdRoute
  ToolsFileCalculatorRoute: typeof ToolsFileCalculatorRoute
  ToolsIrrigationRoute: typeof ToolsIrrigationRoute
  ToolsRubberDamRoute: typeof ToolsRubberDamRoute
  WorkflowSummaryRoute: typeof WorkflowSummaryRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflow': {
      id: '/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof WorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnosis': {
      id: '/diagnosis'
      path: '/diagnosis'
      fullPath: '/diagnosis'
      preLoaderRoute: typeof DiagnosisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anatomy': {
      id: '/anatomy'
      path: '/anatomy'
      fullPath: '/anatomy'
      preLoaderRoute: typeof AnatomyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow_/summary': {
      id: '/workflow_/summary'
      path: '/workflow/summary'
      fullPath: '/workflow/summary'
      preLoaderRoute: typeof WorkflowSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/rubber-dam': {
      id: '/tools/rubber-dam'
      path: '/tools/rubber-dam'
      fullPath: '/tools/rubber-dam'
      preLoaderRoute: typeof ToolsRubberDamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/irrigation': {
      id: '/tools/irrigation'
      path: '/tools/irrigation'
      fullPath: '/tools/irrigation'
      preLoaderRoute: typeof ToolsIrrigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/file-calculator': {
      id: '/tools/file-calculator'
      path: '/tools/file-calculator'
      fullPath: '/tools/file-calculator'
      preLoaderRoute: typeof ToolsFileCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$caseId': {
      id: '/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof CasesCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnatomyRoute: AnatomyRoute,
  DiagnosisRoute: DiagnosisRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  WorkflowRoute: WorkflowRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CasesCaseIdRoute: CasesCaseIdRoute,
  ToolsFileCalculatorRoute: ToolsFileCalculatorRoute,
  ToolsIrrigationRoute: ToolsIrrigationRoute,
  ToolsRubberDamRoute: ToolsRubberDamRoute,
  WorkflowSummaryRoute: WorkflowSummaryRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
