/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowRouteImport } from './routes/workflow'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as DiagnosisRouteImport } from './routes/diagnosis'
import { Route as AnatomyRouteImport } from './routes/anatomy'
import { Route as IndexRouteImport } from './routes/index'

const WorkflowRoute = WorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosisRoute = DiagnosisRouteImport.update({
  id: '/diagnosis',
  path: '/diagnosis',
  getParentRoute: () => rootRouteImport,
} as any)
const AnatomyRoute = AnatomyRouteImport.update({
  id: '/anatomy',
  path: '/anatomy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anatomy': typeof AnatomyRoute
  '/diagnosis': typeof DiagnosisRoute
  '/profile': typeof ProfileRoute
  '/tools': typeof ToolsRoute
  '/workflow': typeof WorkflowRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anatomy': typeof AnatomyRoute
  '/diagnosis': typeof DiagnosisRoute
  '/profile': typeof ProfileRoute
  '/tools': typeof ToolsRoute
  '/workflow': typeof WorkflowRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anatomy': typeof AnatomyRoute
  '/diagnosis': typeof DiagnosisRoute
  '/profile': typeof ProfileRoute
  '/tools': typeof ToolsRoute
  '/workflow': typeof WorkflowRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anatomy'
    | '/diagnosis'
    | '/profile'
    | '/tools'
    | '/workflow'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/anatomy' | '/diagnosis' | '/profile' | '/tools' | '/workflow'
  id:
    | '__root__'
    | '/'
    | '/anatomy'
    | '/diagnosis'
    | '/profile'
    | '/tools'
    | '/workflow'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnatomyRoute: typeof AnatomyRoute
  DiagnosisRoute: typeof DiagnosisRoute
  ProfileRoute: typeof ProfileRoute
  ToolsRoute: typeof ToolsRoute
  WorkflowRoute: typeof WorkflowRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflow': {
      id: '/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof WorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnosis': {
      id: '/diagnosis'
      path: '/diagnosis'
      fullPath: '/diagnosis'
      preLoaderRoute: typeof DiagnosisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anatomy': {
      id: '/anatomy'
      path: '/anatomy'
      fullPath: '/anatomy'
      preLoaderRoute: typeof AnatomyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnatomyRoute: AnatomyRoute,
  DiagnosisRoute: DiagnosisRoute,
  ProfileRoute: ProfileRoute,
  ToolsRoute: ToolsRoute,
  WorkflowRoute: WorkflowRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
